"""Initial migration

Revision ID: ca9f7553c17b
Revises: 
Create Date: 2025-06-04 00:04:50.073717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9f7553c17b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.String(), nullable=True),
    sa.Column('dietary_goal', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_table('dietary_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('target_calories', sa.Integer(), nullable=True),
    sa.Column('target_protein', sa.Float(), nullable=True),
    sa.Column('target_carbs', sa.Float(), nullable=True),
    sa.Column('target_fat', sa.Float(), nullable=True),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fdc_id', sa.String(), nullable=False),
    sa.Column('food_name', sa.String(), nullable=False),
    sa.Column('serving_size', sa.Float(), nullable=False),
    sa.Column('serving_unit', sa.String(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('meal_type', sa.String(), nullable=True),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fdc_id', sa.String(), nullable=False),
    sa.Column('food_name', sa.String(), nullable=False),
    sa.Column('searched_at', sa.DateTime(), nullable=True),
    sa.Column('nutrition_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_history')
    op.drop_table('meal_logs')
    op.drop_table('dietary_goals')
    op.drop_table('users')
    # ### end Alembic commands ###
